name: Executar Notebook Colab

on:
  schedule:
    - cron: '0 8 * * *'  # Executa diariamente às 08:00 UTC (5h BRT)
  workflow_dispatch:  # Permite execução manual

jobs:
  run_colab_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          pip install notebook papermill

      - name: Executar o Notebook
        run: |
          papermill rpa_buscar_nomes_vf.ipynb output.ipynb

      - name: Converter notebook para texto e imprimir saída
        run: |
          jupyter nbconvert output.ipynb --stdout
